package:
  name: test_release2
  version: 0.0.003
  # ToDo Version from script make_relase_github


source:
  path: ../test_release2

build:
  number: 0

requirements:
  build:
    - python=3.7.4
    - setuptools
  run:
    - python=3.7.4
#  script_env:
#   - VERSION
#   - CONDA_BLD_PATH